version: '3'
services:
  linguaDB:
    container_name: linguaDB
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000/tcp"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./data:/app/data
    depends_on:
      - qdrant
  qdrant:
    container_name: qdrant
    image: qdrant/qdrant:latest
    ports:
        - "6333:6333"
        - "6334:6334"
    volumes:
        - ./qdrant_storage:/qdrant/storage


